@extends('layouts.master')

@section('title', $isEdit ? 'Edit Voucher' : 'Tambah Voucher')

@section('container')
<section class="content-header"><h1>{{ $isEdit ? 'Edit Voucher' : 'Tambah Voucher' }}</h1></section>
<section class="content"><form method="POST" action="{{ $isEdit ? route('voucher.update', $voucher) : route('voucher.store') }}"><div class="box box-primary">
    @csrf @if($isEdit) @method('PUT') @endif
    <div class="box-body"><div class="row"><div class="col-md-6"><label>Nama Voucher</label><input name="name" class="form-control" value="{{ old('name', $voucher->name) }}" required></div><div class="col-md-6"><label>Kode Dasar / Kode Voucher</label><input name="code" class="form-control" value="{{ old('code', $voucher->code) }}" required {{ $isEdit ? 'readonly' : '' }}><small>Jika jumlah lebih dari satu, sistem membuat BASE-001, BASE-002, dan seterusnya.</small></div></div>
    <div class="row" style="margin-top:15px"><div class="col-md-3"><label for="voucher-type">Tipe</label><select id="voucher-type" name="type" class="form-control" required><option value="nominal" {{ old('type', $voucher->type) === 'nominal' ? 'selected' : '' }}>Nominal (Rp)</option><option value="percentage" {{ old('type', $voucher->type) === 'percentage' ? 'selected' : '' }}>Percentage (%)</option></select></div><div class="col-md-3"><label>Nilai</label><div class="input-group"><span class="input-group-addon" id="voucher-value-prefix">Rp</span><input name="value" type="text" inputmode="decimal" data-currency-input data-currency-toggle="voucher-type" data-currency-decimals="0" min="0" step="0.01" class="form-control" value="{{ old('value', $voucher->value) }}" required></div></div><div class="col-md-3"><label>Jumlah Voucher</label><input name="quantity" type="number" min="1" max="500" class="form-control" value="{{ old('quantity', 1) }}" {{ $isEdit ? 'disabled' : '' }}><small>Hanya berlaku saat membuat.</small></div><div class="col-md-3"><label>Min. Pembelian</label><div class="input-group"><span class="input-group-addon">Rp</span><input name="min_purchase" type="text" inputmode="numeric" data-currency-input data-currency-decimals="0" min="0" step="0.01" class="form-control" value="{{ old('min_purchase', $voucher->min_purchase) }}"></div></div></div>
    <div class="row" style="margin-top:15px"><div class="col-md-6"><label>Outlet</label><select name="outlet_id" class="form-control"><option value="">Semua outlet</option>@foreach($outlets as $outlet)<option value="{{ $outlet->id }}" {{ old('outlet_id', $voucher->outlet_id) == $outlet->id ? 'selected' : '' }}>{{ $outlet->name }}</option>@endforeach</select><small>Kosongkan untuk voucher global.</small></div><div class="col-md-6"><label>Produk (opsional)</label><select name="product_id" class="form-control"><option value="">Semua produk</option>@foreach($products as $product)<option value="{{ $product->id }}" {{ old('product_id', $voucher->product_id) == $product->id ? 'selected' : '' }}>{{ $product->code }} — {{ $product->name }}</option>@endforeach</select></div></div>
    <div class="row" style="margin-top:15px"><div class="col-md-3"><label>Maks. Potongan</label><div class="input-group"><span class="input-group-addon">Rp</span><input name="max_discount_amount" type="text" inputmode="numeric" data-currency-input data-currency-decimals="0" min="0" step="0.01" class="form-control" value="{{ old('max_discount_amount', $voucher->max_discount_amount) }}"></div><small>Opsional, terutama untuk percentage.</small></div><div class="col-md-9"><label>Deskripsi</label><input name="desc" class="form-control" value="{{ old('desc', $voucher->desc) }}"></div></div>
    <div class="form-group" style="margin-top:15px"><label>Rentang Aktif</label><input type="text" name="daterange" id="daterange" class="form-control" value="{{ old('daterange', $voucher->start_at && $voucher->end_at ? $voucher->start_at->format('Y-m-d H:i') . ' - ' . $voucher->end_at->format('Y-m-d H:i') : '') }}"><small>Kosongkan bila tidak dibatasi tanggal.</small></div>
    </div><div class="box-footer"><a href="{{ route('voucher.index') }}" class="btn btn-default">Kembali</a> <button class="btn btn-primary">Simpan</button></div>
</div></form></section>
@endsection
@section('page-script')<script>
$(function(){ $('#daterange').daterangepicker({timePicker:true,timePickerIncrement:30,autoUpdateInput:false,locale:{format:'YYYY-MM-DD HH:mm',cancelLabel:'Clear'}}).on('apply.daterangepicker',function(ev,picker){$(this).val(picker.startDate.format('YYYY-MM-DD HH:mm')+' - '+picker.endDate.format('YYYY-MM-DD HH:mm'));}).on('cancel.daterangepicker',function(){$(this).val('');}); $('#voucher-type').on('change', function(){ $('#voucher-value-prefix').text(this.value === 'percentage' ? '%' : 'Rp'); window.initCurrencyInputs?.(); }); $('#voucher-value-prefix').text($('#voucher-type').val() === 'percentage' ? '%' : 'Rp'); });
</script>@endsection
